# -*- coding: utf-8 -*-
"""DISEÑO_SERIE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tj0ARAzOJY2ggTJV4hBMcfcEetjuM1Pj
"""

import math

# =============================================================================
#  DISEÑO DE TUBERÍAS EN SERIE
#  Ingrese los datos directamente en esta sección
# =============================================================================

# --- DATOS GENERALES ---------------------------------------------------------

CABEZA_TOTAL    = 35.843      # [metros de agua columna, mca]
CABEZA_LLEGADA  = 0.0       # [metros de agua columna, mca]
DENSIDAD        = 999.1    # [kg/m³]
VISCOSIDAD      = 0.00114     # [Pa·s  =  kg/(m·s)]

# --- DIÁMETROS DISPONIBLES ---------------------------------------------------
# Lista de diámetros comerciales entre los cuales el programa elegirá
# Unidad: metros [m]

DIAMETROS_DISPONIBLES = [0.050, 0.075, 0.100, 0.125, 0.150, 0.200, 0.250, 0.300, 0.350, 0.400, 0.450, 0.500]

# --- TUBERÍAS ----------------------------------------------------------------
# Cada tubería es un diccionario con cuatro campos:
#   longitud      [m]       longitud de la tubería
#   rugosidad     [m]       rugosidad absoluta de la pared
#   coef_menores  [-]       suma de coeficientes K de pérdidas menores
#   caudal_lat    [m³/s]    caudal lateral que sale en ese nodo
#                           (la ÚLTIMA tubería debe tener caudal_lat > 0,
#                            ese valor es el caudal terminal)

TUBERIAS = [
    {"longitud": 350.0, "rugosidad": 1.5e-6, "coef_menores": 7.9, "caudal_lat": 45.1e-3},
    {"longitud": 123.0, "rugosidad": 1.5e-6, "coef_menores": 3.3, "caudal_lat": 39.0e-3},
    {"longitud": 174.0, "rugosidad": 1.5e-6, "coef_menores": 3.5, "caudal_lat": 73.2e-3},
]

# =============================================================================
#  MOTOR DE CÁLCULO  —  no es necesario modificar nada de aquí en adelante
# =============================================================================

PI              = math.pi
_4_SOBRE_PI     = 4.0 / PI
_PI_SOBRE_4     = PI / 4.0
G2              = 2.0 * 9.806          # 2g  [m/s²]
PASO_D          = 0.0001               # paso de búsqueda de diámetro [m]
SEMILLA_D       = 0.010                # diámetro inicial de búsqueda  [m]


def _fr_laminar(re):
    return 64.0 / re


def _fr_transicional(d, r, re):
    rel = r / d
    y3  = -0.86859 * math.log(rel / 3.7 + 5.74 / (4000.0 ** 0.9))
    fa  = y3 ** -2.0
    y2  = rel / 3.7 + 5.74 / (re ** 0.9)
    fb  = (2.0 - 0.00514215 / (y2 * y3)) * fa
    rv  = re / 2000.0
    x1  =  7.0 * fa - fb
    x2  =  0.128 - 17.0 * fa + 2.5  * fb
    x3  = -0.128 + 13.0 * fa - 2.0  * fb
    x4  =  0.032 -  3.0 * fa + 0.5  * fb
    return ((x4 * rv + x3) * rv + x2) * rv + x1


def _fr_turbulento(d, r, re):
    f = 0.012
    for _ in range(31):
        f = (-2.0 * math.log10(r / (3.7 * d) + 2.51 / (re * math.sqrt(f)))) ** -2.0
    return f


def factor_friccion(d, r, re):
    if re < 2000.0:
        return _fr_laminar(re)
    if re <= 4000.0:
        return _fr_transicional(d, r, re)
    return _fr_turbulento(d, r, re)


def velocidad_desde_friccion(nu, r, L, d, hf):
    raiz = math.sqrt(G2 * d * hf / L)
    return -2.0 * raiz * math.log10(r / (3.7 * d) + 2.51 * nu / (d * raiz))


def resolver_diametro(h, dAvail, L, nu, r, k, Q):
    """Devuelve el menor diámetro de dAvail capaz de conducir Q con cabeza h."""
    for d in dAvail:
        vel_men = _4_SOBRE_PI * Q / (d ** 2.0)
        pm      = k * (vel_men ** 2.0) / G2
        if pm >= h:
            continue
        hf  = h - pm
        vf  = velocidad_desde_friccion(nu, r, L, d, hf)
        cap = _PI_SOBRE_4 * (d ** 2.0) * vf
        if cap >= Q:
            return d
    raise ValueError(
        "Ningún diámetro disponible es suficiente para la cabeza dada. "
        "Agregue diámetros mayores a DIAMETROS_DISPONIBLES."
    )


def calcular(cabeza_total, cabeza_llegada, densidad, viscosidad,
             tuberias, diametros):

    # --- validaciones básicas ------------------------------------------------
    if cabeza_total <= cabeza_llegada:
        raise ValueError("CABEZA_TOTAL debe ser mayor que CABEZA_LLEGADA.")
    if densidad <= 0:
        raise ValueError("DENSIDAD debe ser > 0.")
    if viscosidad <= 0:
        raise ValueError("VISCOSIDAD debe ser > 0.")
    n = len(tuberias)
    if n == 0:
        raise ValueError("Debe definir al menos una tubería.")
    if tuberias[-1]["caudal_lat"] <= 0:
        raise ValueError("El caudal_lat de la ÚLTIMA tubería (caudal terminal) debe ser > 0.")
    if len(diametros) == 0:
        raise ValueError("DIAMETROS_DISPONIBLES no puede estar vacío.")

    dAvail = sorted(diametros)
    nu     = viscosidad / densidad
    cab    = cabeza_total - cabeza_llegada           # cabeza disponible [mca]

    # --- caudales reales (de aguas abajo hacia arriba) -----------------------
    q_real = [0.0] * n
    q_real[-1] = tuberias[-1]["caudal_lat"]
    for i in range(n - 2, -1, -1):
        q_real[i] = q_real[i + 1] + tuberias[i]["caudal_lat"]

    Ls = [t["longitud"]     for t in tuberias]
    Rs = [t["rugosidad"]    for t in tuberias]
    Ks = [t["coef_menores"] for t in tuberias]
    sumL = sum(Ls)

    # --- 1ª iteración: cabeza proporcional a la longitud ---------------------
    h_asig  = [cab * L / sumL for L in Ls]
    D       = [0.0] * n
    p_may   = [0.0] * n
    p_men   = [0.0] * n

    for i in range(n):
        D[i]     = resolver_diametro(h_asig[i], dAvail, Ls[i], nu, Rs[i], Ks[i], q_real[i])
        v        = _4_SOBRE_PI * q_real[i] / D[i] ** 2
        re       = v * D[i] / nu
        f        = factor_friccion(D[i], Rs[i], re)
        p_may[i] = f * Ls[i] * v ** 2 / (D[i] * G2)
        p_men[i] = Ks[i] * v ** 2 / G2

    residual = cab - sum(p_may) - sum(p_men)

    # --- 2ª iteración: corrección con residual -------------------------------
    for i in range(n):
        h_corr = p_may[i] + residual
        dc     = resolver_diametro(h_corr, dAvail, Ls[i], nu, Rs[i], Ks[i], q_real[i])
        if dc != D[i]:
            D[i]     = dc
            v        = _4_SOBRE_PI * q_real[i] / D[i] ** 2
            re       = v * D[i] / nu
            f        = factor_friccion(D[i], Rs[i], re)
            p_may[i] = f * Ls[i] * v ** 2 / (D[i] * G2)
            p_men[i] = Ks[i] * v ** 2 / G2
            residual = cab - sum(p_may) - sum(p_men)

    return {
        "n"          : n,
        "cab_disp"   : cab,
        "q_real"     : q_real,
        "diametros_m": D,
        "p_mayores"  : p_may,
        "p_menores"  : p_men,
    }


def imprimir_resultados(res):
    n        = res["n"]
    cab      = res["cab_disp"]
    Q        = res["q_real"]
    D        = res["diametros_m"]
    pm       = res["p_mayores"]
    pn       = res["p_menores"]
    total_pm = sum(pm)
    total_pn = sum(pn)

    sep  = "─" * 72
    sep2 = "═" * 72

    print()
    print(sep2)
    print("  DISEÑO DE TUBERÍAS EN SERIE — RESULTADOS")
    print(sep2)
    print(f"  Cabeza disponible : {cab:.4f} mca")
    print(sep)
    print(f"  {'Tubería':^8}  {'Caudal [m³/s]':>14}  {'Diámetro [mm]':>14}"
          f"  {'Pérd. mayor [mca]':>18}  {'Pérd. menor [mca]':>18}")
    print(sep)
    for i in range(n):
        print(f"  {i+1:^8}  {Q[i]:>14.6f}  {D[i]*1000:>14.4f}"
              f"  {pm[i]:>18.4f}  {pn[i]:>18.4f}")
    print(sep)
    print(f"  {'TOTAL':^8}  {'':>14}  {'':>14}"
          f"  {total_pm:>18.4f}  {total_pn:>18.4f}")
    print(sep2)
    print()


# =============================================================================
#  EJECUCIÓN
# =============================================================================

resultado = calcular(
    CABEZA_TOTAL,
    CABEZA_LLEGADA,
    DENSIDAD,
    VISCOSIDAD,
    TUBERIAS,
    DIAMETROS_DISPONIBLES,
)

imprimir_resultados(resultado)